\i setup.sql;
-- \i test/trigger_1.sql;
-- \i test/trigger_2.sql;
-- \i test/trigger_3.sql;
-- \i test/trigger_4.sql;
-- \i test/trigger_5.sql;
-- \i test/trigger_6.sql;
-- \i test/trigger_7.sql;
-- \i test/trigger_8.sql;
-- \i test/trigger_9.sql;
-- \i test/trigger_10.sql;
-- \i test/trigger_11.sql;
-- \i test/trigger_12.sql;
-- \i test/trigger_13.sql;
-- \i test/trigger_14.sql;
\i test/submit_requests.sql;